version: '3.1'
services:
  db:
    container_name: db
    networks:
      - backend
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /Users/john.a.piedrahita/Documents/Volumes/Surveys/mongo:/data/db
  api:
    container_name: api
    networks:
      - backend
    build:
      context: .
      dockerfile: ./src/deployment/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - MONGO_DEVELOPMENT=mongodb://db:27017/surveys
    command: sh -c "npm install && npm run watch"

volumes:
  data01:
    driver: local

networks:
  backend:
    driver: bridge